settings:
  title: 'jymuoyu-Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: 20210111_172252.jpg # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: f-jymuoyu # unique identifier
    name: 茶水间
    description: 'Misskey-茶水间~来摸鱼吧' # default=empty
    url: 'https://f.jymuoyu.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: e-jymuoyu
    name: 小饭馆
    description: 'Pleroma-打工人小饭馆'
    url: 'https://e.jymuoyu.com/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: m-jymuoyu
    name: Matrix-jymuoyu
    url: 'https://jymuoyu.com/'
    method: GET
    expectStatus: 200
    linkable: false
